### ISSUE TITLE
[postcss] Rule is not a constructor

### ISSUE THREAD

**Issue by gRoberts84** [thedevdojo/genesis#15]
Hi there,

I've just tried setting up Genesis on a fresh installation and unfortunately I've hit a snag:

```
10:33:47 AM [vite] Internal server error: [postcss] Rule is not a constructor
  Plugin: vite:css
  File: /Users/gavinroberts/Projects/volt-genesis/resources/css/app.css?direct
      at pickDeclarations (/Users/gavinroberts/Projects/volt-genesis/node_modules/postcss-nested/index.js:120:16)
      at /Users/gavinroberts/Projects/volt-genesis/node_modules/postcss-nested/index.js:308:21
      at /Users/gavinroberts/Projects/volt-genesis/node_modules/tailwindcss/node_modules/postcss/lib/container.js:98:44
      at Rule.each (/Users/gavinroberts/Projects/volt-genesis/node_modules/tailwindcss/node_modules/postcss/lib/container.js:53:16)
      at Proxy.<anonymous> (/Users/gavinroberts/Projects/volt-genesis/node_modules/tailwindcss/node_modules/postcss/lib/container.js:95:30)
      at Rule (/Users/gavinroberts/Projects/volt-genesis/node_modules/postcss-nested/index.js:305:12)
      at LazyResult.visitSync (/Users/gavinroberts/Projects/volt-genesis/node_modules/tailwindcss/node_modules/postcss/lib/lazy-result.js:448:19)
      at LazyResult.walkSync (/Users/gavinroberts/Projects/volt-genesis/node_modules/tailwindcss/node_modules/postcss/lib/lazy-result.js:531:20)
      at /Users/gavinroberts/Projects/volt-genesis/node_modules/tailwindcss/node_modules/postcss/lib/lazy-result.js:525:39
      at Root.each (/Users/gavinroberts/Projects/volt-genesis/node_modules/tailwindcss/node_modules/postcss/lib/container.js:53:16)
```

**PHP:** 8.2.6
**NPM:** 9.6.4
**Node:** v20.1.0
**Laravel:** 10.18.0

<img width="899" alt="image" src="https://github.com/thedevdojo/genesis/assets/348184/635e0788-9053-4e88-9db4-df3986d3d850">

Am I missing anything?

**Comment by tnylea** [comment]
Hey @gRoberts84 

Have you added anything else to your `app.css` file. If so, can you share what you've added. Can you also try and remove your `node_modules` folder and re-run `npm install`.

Finally, can you share with me which version of PostCSS is installed inside of your package-lock.json. Search for "postcss" and you should find something that looks like this:

```
"peerDependencies": {
    "postcss": "^8.1.0"
}
```

Let me know what you have and I'll try and help you out more 😉

Thanks!

**Comment by tnylea** [comment]
Hey @gRoberts84, were you able to get this issue resolved?

Let me know the answers to the question from my previous reply 🤙

**Comment by tnylea** [comment]
Closing for now, if this is still an issue please feel free to let us know 😉
